// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqKv_YRZAzy09Zf89Xb3v8DnurEaTKMS8',
    appId: '1:570515445310:web:4677e36794f7a13fae636f',
    messagingSenderId: '570515445310',
    projectId: 'send-aeebc',
    authDomain: 'send-aeebc.firebaseapp.com',
    storageBucket: 'send-aeebc.appspot.com',
    measurementId: 'G-T85F1TFBBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbq84t9LTJk67AUJ79qYVq8aiVNgREDrU',
    appId: '1:570515445310:android:d7c6b0e44b8cb647ae636f',
    messagingSenderId: '570515445310',
    projectId: 'send-aeebc',
    storageBucket: 'send-aeebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOItQyhGA1eua-0FZaTAtWmfBdaualCn4',
    appId: '1:570515445310:ios:112c0c136283eef7ae636f',
    messagingSenderId: '570515445310',
    projectId: 'send-aeebc',
    storageBucket: 'send-aeebc.appspot.com',
    androidClientId: '570515445310-5aaaeo9a78d3qbmct7srnne88kvun7l2.apps.googleusercontent.com',
    iosClientId: '570515445310-qhl645jcj0h06j2vajgclp6h2cijnmjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mantravatProject',
  );
}
